// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComputerID() {
  return window['go']['main']['App']['ComputerID']();
}

export function SendMsg(arg1) {
  return window['go']['main']['App']['SendMsg'](arg1);
}
